Android degoogling
thecoshman/degoogle pull request #2
Opened 2017-11-20 15:03 UTC by milleniumbug

2018-01-16 16:13 UTC, thecoshman requested changes

2018-01-16 16:13 UTC, thecoshman commented on Android.md
> +Open source-only distro of Android, which means it has even less chance of working on your device.
'even less' is comparative, what are you comparing it to?

These are two possible alternate ROMs so perhaps put them under a common `#` heading and put these at a lower sub heading level

2018-01-16 16:15 UTC, nabijaczleweli commented on Android.md
> +Open source-only distro of Android, which means it has even less chance of working on your device.
>what are you comparing it to?

LineageOS, probably.

2018-01-16 16:17 UTC, milleniumbug commented on Android.md
> +Open source-only distro of Android, which means it has even less chance of working on your device.
Yeah, the intent was to compare it with LineageOS, but I'll amend this.

2018-04-12 18:47 UTC, nabijaczleweli commented on Android.md
> +- Aptoide. Likely to have a ton of **unofficially** republished applications from Google Play. Trust them on your own risk.
"At your own risk", innit?

2018-04-13 09:30 UTC, thecoshman approved these changes

2018-04-13 09:30 UTC, merged